package chcm.mid.his2cris.gather.commit.trigger;

public class CheckItemSQL {

	public String getCheckItems(String orgNo, String examItem) {
		return "SELECT  ORGNO, EXAMITEM, TCNAME,\n"
				+ "        CASE WHEN EMPTYSTOMACH IS NULL OR TRIM(EMPTYSTOMACH) = '' THEN 'N' ELSE EMPTYSTOMACH END EMPTYSTOMACH,\n"
				+ "        CASE WHEN ISAUTOSCHEDULE IS NULL OR TRIM(ISAUTOSCHEDULE) = '' THEN 'N' ELSE ISAUTOSCHEDULE END ISAUTOSCHEDULE,\n"
				+ "        CASE WHEN TOHOSPITAL IS NULL OR TRIM(TOHOSPITAL) = '' THEN 'N' ELSE TOHOSPITAL END TOHOSPITAL,\n"
				+ "        IFNULL(TRIM(EXAMPRIORITY),9999) EXAMPRIORITY\n"
				+ " FROM DB2INST1.CMNBEXAMITEMDATATBL A\n"
				+ " WHERE A.ACTIVEFLAG = '0'\n"
				+ "   AND A.ORGNO = '"+orgNo+"' AND A.EXAMITEM = '"+examItem+"'";
	}

	public String getNewCheckItems(String orgNo, String examItems) {
		return "SELECT  ORGNO, EXAMITEM, TCNAME,\n"
				+ "        CASE WHEN EMPTYSTOMACH IS NULL OR TRIM(EMPTYSTOMACH) = '' THEN 'N' ELSE EMPTYSTOMACH END EMPTYSTOMACH,\n"
				+ "        CASE WHEN ISAUTOSCHEDULE IS NULL OR TRIM(ISAUTOSCHEDULE) = '' THEN 'N' ELSE ISAUTOSCHEDULE END ISAUTOSCHEDULE,\n"
				+ "        CASE WHEN TOHOSPITAL IS NULL OR TRIM(TOHOSPITAL) = '' THEN 'N' ELSE TOHOSPITAL END TOHOSPITAL,\n"
				+ "        IFNULL(TRIM(EXAMPRIORITY),9999) EXAMPRIORITY\n"
				+ " FROM DB2INST1.CMNBEXAMITEMDATATBL A\n"
				+ " WHERE A.ACTIVEFLAG = '0'\n"
				+ "   AND A.ORGNO = '"+orgNo+"' AND A.EXAMITEM IN ("+examItems+")\n";
	}
}
